image: docker:stable
services:
  - docker:dind

stages:
  - build jar
  - build and push docker image
  - deploy

build:
  tags:
    - space
  stage: build jar
  image: openjdk:14
  before_script:
    - echo "Building jar"
    - chmod +x ./gradlew
  script:
    - ./gradlew assemble
  artifacts:
      paths:
        - build/libs/*.jar

docker build:
  tags:
    - space  
  image: docker:19.03.8
  stage: build and push docker image
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.8-dind
  before_script:
    - echo "Building and pushing docker image"
    - docker info
  script:
    - docker build -t receiptanalysis/backend .
    - echo $DOCKER_PASS | docker login -u$DOCKER_USER --password-stdin
    - docker push receiptanalysis/backend
    - docker logout

deploy:
  tags:
    - space  
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 13.53.140.53 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "Deploying"
  script:
    - scp -i $SSH_PUBLIC_KEY docker-compose.prod.yml ubuntu@13.53.140.53:/home/ubuntu/docker-compose.backend.yml
    - ssh -i $SSH_PUBLIC_KEY ubuntu@13.53.140.53
    - docker pull receiptanalysis/backend
    - docker stop analysis-backend && docker rm analysis-backend && docker-compose -f docker-compose.backend.yml up -d backend
    - docker logout
