version: "3.7"

services:

  backend:
    image: receiptanalysis/backend
    restart: always
    container_name: "analysis-backend"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/analysis
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_PROFILES_ACTIVE=prod
      - OCR_URL=http://ocr:5000/
      - HOST=receipt.modalstudio.com
      - BASEPATH=/api
      - LOGGING_LEVEL_ROOT=INFO
      - FILE_LIMIT=100
    volumes:
      - analysis-back-logs:/logs
      - analysis-back-files:/files

  ocr:
    image: receiptanalysis/ocr
    restart: always
    container_name: "analysis-ocr"
    volumes:
      - analysis-ocr-files:/home/files

  db:
    image: postgres
    restart: always
    container_name: "analysis-db"
    ports:
      - "8999:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=analysis
    volumes:
      - analysis-db-data:/var/lib/postgresql/data

volumes:
  analysis-db-data:
  analysis-back-logs:
  analysis-back-files:
  analysis-ocr-files:
