spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/analysis
    driverClassName: org.postgresql.Driver
    username: postgres
    password: development
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
logging:
  file:
    path: ./logs
  level:
    root: INFO
    org.apache.tomcat: INFO
    org.apache.catalina: INFO
server:
  tomcat:
    basedir: .
    accesslog:
      suffix: .log
      enabled: true
      prefix: access_log
      directory: logs
      pattern: common
      file-date-format: .yyyy-MM-dd
      buffered: false
