spring:
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans,heapdump,logfile,loggers,threaddump,shutdown"
    jmx:
      exposure:
        exclude: "*"
